[package]
name = "stalwart-cli"
description = "Stalwart CLI"
version = "1.0.6"
authors = ["Stalwart Labs LLC <hello@stalw.art>"]
license = "AGPL-3.0-only OR LicenseRef-SEL"
repository = "https://github.com/stalwartlabs/cli"
homepage = "https://github.com/stalwartlabs/cli"
edition = "2024"
readme = "README.md"

[package.metadata.wix]
upgrade-guid = "A23CF3C0-DD43-4575-9794-DD1EC6051C6F"
path-guid = "571AF523-511D-45E0-BB08-41A038672DE2"
license = false
eula = false

[dependencies]
ahash = { version = "0.8.12", features = ["serde"] }
anyhow = "1.0.102"
base64 = "0.22.1"
clap = { version = "4.6", features = ["derive", "env"] }
dirs = "6"
flate2 = "1.1.9"
is-terminal = "0.4.17"
reqwest = { version = "0.13.2", default-features = false, features = ["blocking", "rustls", "json"] }
rpassword = "7.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
sha2 = "0.11"
thiserror = "2"

[[bin]]
name = "stalwart-cli"
path = "src/main.rs"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.dist]
inherits = "release"
lto = "thin"
